services:
  collector:
    build: ./collector
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - GROUP_ID=${GROUP_ID}

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./content:/app/content

  frontend:
    build: ./frontend
    restart: unless-stopped
