services:
  collector:
    build: ./collector
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - GROUP_ID=${GROUP_ID}
    networks:
      - default

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./content:/app/content
    networks:
      - default

  frontend:
    build: ./frontend
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    external: true
    name: easypanel-n8n_karpix # <--- ИМЯ СЕТИ ВАШЕЙ БАЗЫ ДАННЫХ
